# Exercise 5.2

In [1]:
import numpy as np

## 5.2 (a)

In [2]:
def UtoSU4 (U):
    # To Do: define alpha such that alpha*U lies in SU(4).
    # Hint: if you use np.power(x1, x2, dtype=complex), make sure you cast the data type as complex
    alpha = 1
    return alpha * U

## 5.2 (b)

In [13]:
Q = 1/np.sqrt(2)*np.array([[1,  0,  0,  1j],
                           [0, 1j,  1,   0],
                           [0, 1j, -1,   0],
                           [1,  0,  0, -1j]])

def U_B (U):
    # To Do: write the transformation.
    # Hint: Q above might be useful.
    U_B = U
    return U_B

## 5.2 (e)

In [4]:
def m(U_B):
    #To Do: write the definition of m
    m = U_B    
    return m

## 5.2 (f)

In [16]:
def compute_c(U):
    # To Do: program the method
    c = np.array([0.,0.,0.])
    
    return c

In [17]:
compute_c(np.diag([1,1,1,1]))

array([0., 0., 0.])

## 5.2 (g)

In [18]:
def compute_t_in_Weyl_chamber(U):
    c = compute_c(U)

    # Aim: bring c into the Weyl chamber. We will work in t\in[-1,1] units.
    # Step 0: work in terms of multiple of pi
    t = c/np.pi

    # To Do: Step 1: Bring everything into [0, 1)
    t = t
    # To Do: Step 2: Sort t1 >= t2 >= t3
    t =t
    # To Do: Step 3: if t1 + t2 >= 1, transform (t1, t2, t3) -> (1-t2, 1-t1, t3)
    if t[0]+t[1] >=1:
        t = t
    # To Do: Step 4: if t3 = 0 and t1>1/2, transform (t1, t2, 0) -> (1-t1, t2, 0)
    if (t[0] > 1/2) and np.isclose(t[2], 0):
        t = t
    return t

## 5.2 (h)

In [19]:
CNOT = np.array([[1,0,0, 0],
                 [0,1,0,0],
                 [0,0,0,1],
                 [0,0,1,0]])

SWAP = np.array([[1,0,0, 0],
                 [0,0,1,0],
                 [0,1,0,0],
                 [0,0,0,1]])

iSWAP = np.array([[1,0,0, 0],
                 [0,0,1j,0],
                 [0,1j,0,0],
                 [0,0,0,1]])

sqrtSWAP = np.array([[1,0,0, 0],
                 [0,1/2 * (1+1j),1/2 * (1-1j),0],
                 [0,1/2 * (1-1j),1/2 * (1+1j),0],
                 [0,0,0,1]])

In [20]:
compute_t_in_Weyl_chamber(CNOT)

array([0., 0., 0.])

In [21]:
compute_t_in_Weyl_chamber(SWAP)

array([0., 0., 0.])

In [22]:
compute_t_in_Weyl_chamber(iSWAP)

array([0., 0., 0.])

In [23]:
compute_t_in_Weyl_chamber(sqrtSWAP)

array([0., 0., 0.])